apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-car
  namespace: argocd  # ArgoCD installs its resources in the `argocd` namespace
  labels:
    example: basic
spec:
  project: default
  source:
    repoURL: https://github.com/alvo254/kodi.git  # Replace with your repository URL
    targetRevision: HEAD  # Branch, tag, or commit SHA
    path: "package/manifests"  # Path to the manifests in the repository
  destination:
    server: https://kubernetes.default.svc  # In-cluster Kubernetes API server
    namespace: frontend  # Namespace where the Deployment is deployed
  syncPolicy:
    automated:
      selfHeal: true  # Automatically correct drift
    syncOptions:
      - CreateNamespace=true  # Create the namespace if it doesn't exist